apiVersion: apps/v1
kind: Deployment
metadata:
  name: webserver-deploy
  labels:
    app: webserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webserver
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: webserver
    spec:
      containers:
      - image: httpd
        name: webserver
        ports:
        - containerPort: 8000
          name: webserver
        volumeMounts:
        - name: webserver-vol
          mountPath: /usr/local/apache2/htdocs/
      volumes:
        - name: webserver-vol
          persistentVolumeClaim:
            claimName: webserver-vol
