apiVersion: apps/v1
kind: Deployment
metadata:
  name: webserver-deploy
  labels:
    app: webserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webserver
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: webserver
    spec:
      containers:
      - image: httpd
        name: webserver
